/** Mirrors frontend `categorizeIngredient` for catalog grouping. */
export type IngredientGroupId =
  | "meat"
  | "seafood"
  | "vegetables"
  | "fruits"
  | "dairy"
  | "grains"
  | "legumes"
  | "spices"
  | "baking"
  | "other";

const RULES: { group: IngredientGroupId; keywords: string[] }[] = [
  {
    group: "meat",
    keywords: [
      "chicken",
      "beef",
      "pork",
      "lamb",
      "mutton",
      "duck",
      "turkey",
      "bacon",
      "ham",
      "sausage",
      "mince",
      "steak",
      "veal",
      "venison",
      "goose",
      "prosciutto",
      "chorizo",
      "salami",
      "meat",
      "liver",
      "kidney",
      "brisket",
    ],
  },
  {
    group: "seafood",
    keywords: [
      "salmon",
      "tuna",
      "cod",
      "prawn",
      "shrimp",
      "crab",
      "lobster",
      "fish",
      "anchovy",
      "sardine",
      "mussel",
      "clam",
      "oyster",
      "squid",
      "octopus",
      "haddock",
      "trout",
      "seafood",
      "crayfish",
    ],
  },
  {
    group: "vegetables",
    keywords: [
      "tomato",
      "potato",
      "onion",
      "garlic",
      "carrot",
      "pepper",
      "cabbage",
      "spinach",
      "lettuce",
      "cucumber",
      "mushroom",
      "broccoli",
      "cauliflower",
      "celery",
      "leek",
      "pumpkin",
      "zucchini",
      "courgette",
      "aubergine",
      "eggplant",
      "beet",
      "turnip",
      "radish",
      "asparagus",
      "corn",
      "pea",
      "bean sprout",
      "kale",
      "chard",
    ],
  },
  {
    group: "fruits",
    keywords: [
      "apple",
      "banana",
      "orange",
      "lemon",
      "lime",
      "berry",
      "grape",
      "mango",
      "peach",
      "pear",
      "plum",
      "apricot",
      "pineapple",
      "melon",
      "watermelon",
      "cherry",
      "strawberry",
      "blueberry",
      "raspberry",
      "blackberry",
      "cranberry",
      "fig",
      "date",
      "raisin",
      "prune",
      "coconut",
      "avocado",
    ],
  },
  {
    group: "dairy",
    keywords: [
      "milk",
      "cheese",
      "butter",
      "cream",
      "yogurt",
      "yoghurt",
      "egg",
      "custard",
      "cheddar",
      "mozzarella",
      "parmesan",
      "feta",
      "ricotta",
      "mascarpone",
      "ghee",
    ],
  },
  {
    group: "grains",
    keywords: [
      "rice",
      "pasta",
      "noodle",
      "flour",
      "bread",
      "oat",
      "barley",
      "quinoa",
      "couscous",
      "bulgur",
      "semolina",
      "spaghetti",
      "macaroni",
      "tortilla",
      "wrap",
      "breadcrumb",
    ],
  },
  {
    group: "legumes",
    keywords: [
      "lentil",
      "chickpea",
      "bean",
      "peanut",
      "almond",
      "walnut",
      "cashew",
      "pecan",
      "hazelnut",
      "pistachio",
      "tofu",
      "tempeh",
      "soy",
    ],
  },
  {
    group: "spices",
    keywords: [
      "salt",
      "pepper",
      "cumin",
      "paprika",
      "chili",
      "chilli",
      "cinnamon",
      "nutmeg",
      "ginger",
      "garlic powder",
      "onion powder",
      "oregano",
      "basil",
      "thyme",
      "rosemary",
      "parsley",
      "coriander",
      "cilantro",
      "turmeric",
      "cardamom",
      "clove",
      "bay",
      "saffron",
      "vanilla",
      "vinegar",
      "soy sauce",
      "mustard",
      "honey",
    ],
  },
  {
    group: "baking",
    keywords: [
      "sugar",
      "chocolate",
      "cocoa",
      "baking powder",
      "baking soda",
      "yeast",
      "icing",
      "frosting",
      "jam",
      "marmalade",
      "gelatin",
      "molasses",
      "treacle",
      "caster",
      "icing sugar",
    ],
  },
];

export function categorizeIngredient(name: string): IngredientGroupId {
  const lower = name.toLowerCase();
  for (const { group, keywords } of RULES) {
    if (keywords.some((kw) => lower.includes(kw))) return group;
  }
  return "other";
}
