import {
  Bookmark,
  BookOpen,
  Calendar,
  Home,
  Search,
  ShoppingCart,
} from "lucide-react";

export const ALLERGENS = [
  { id: "gluten", label: "Gluten", emoji: "🌾" },
  { id: "dairy", label: "Dairy", emoji: "🥛" },
  { id: "nuts", label: "Nuts", emoji: "🥜" },
];

export const CATEGORIES = [
  "Үндэсний хоол",
  "Шөл",
  "Талх, бялуу",
  "Цагаан хоол",
  "Амттан",
  "Уух зүйл",
];

export const NAV_ITEMS = [
  { icon: Home, label: "Нүүр", href: "/", active: true },
  { icon: Search, label: "Хайх", href: "/search", active: false },
  { icon: Bookmark, label: "Хадгалсан", href: "/saved", active: false },
  {
    icon: BookOpen,
    label: "Миний хоолны дэвтэр",
    href: "/my-recipes",
    active: false,
  },
  {
    icon: Calendar,
    label: "Долоо хоногийн төлөвлөгөө",
    href: "/planner",
    active: false,
  },
  {
    icon: ShoppingCart,
    label: "Дэлгүүрийн жагсаалт",
    href: "/shopping",
    active: false,
  },
];

import type { Recipe } from "@/lib/types";

export const MOCK_RECIPES: Recipe[] = [
  {
    _id: "1",
    isFeatured: true,
    title: "Хорхог — гэр бүлийн уламжлалт",
    description:
      "Хадны нунтаг, эрх, бүх найрлагатай уламжлалт халуун чулуун дотор болгосон үхрийн махан хорхог.",
    author: { name: "Д. Нарантуяа" },
    categories: ["Үндэсний хоол", "Уламжлалт"],
    tags: ["Мах"],
    cookTime: 90,
    prepTime: 30,
    servings: 6,
    difficulty: "hard",
    rating: 4.8,
    reviewCount: 142,
    allergens: [],
    ingredients: [
      { name: "Хонины мах", amount: "2", unit: "кг" },
      { name: "Төмс", amount: "6", unit: "ширхэг" },
      { name: "Лууван", amount: "3", unit: "ширхэг" },
      { name: "Сонгино", amount: "2", unit: "ширхэг" },
      { name: "Давс", amount: "2", unit: "хш" },
      { name: "Халуун чулуу", amount: "10", unit: "ширхэг" },
    ],
    steps: [
      { order: 1, instruction: "Махыг том хэсгүүдэд хэрчиж, давсаар амтална." },
      { order: 2, instruction: "Халуун чулууг галд улайтал халаана." },
      {
        order: 3,
        instruction:
          "Тогоонд мах, хүнсний ногооны давхаргуудыг ээлжлэн тавина.",
      },
      { order: 4, instruction: "Улайсан чулуудыг махны дунд тавина." },
      { order: 5, instruction: "Тогоог битүүмжилж 90 минут буцалгана." },
    ],
  },
  {
    _id: "2",
    isPremium: true,
    title: "Бананы панна котта",
    description: "Нарийн бодисоор хийсэн нэмэлт чихэргүй бананы панна котта.",
    author: { name: "Б. Чимэгэрдэнэ" },
    categories: ["Цайны зүйл"],
    tags: ["Солонго"],
    cookTime: 20,
    prepTime: 10,
    servings: 4,
    difficulty: "easy",
    rating: 4.6,
    reviewCount: 89,
    allergens: ["dairy"],
    ingredients: [
      { name: "Сүү", amount: "500", unit: "мл" },
      { name: "Банан", amount: "2", unit: "ширхэг" },
      { name: "Желатин", amount: "10", unit: "гр" },
      { name: "Чихэр", amount: "3", unit: "хш" },
      { name: "Ванилин", amount: "1", unit: "хш" },
    ],
    steps: [
      { order: 1, instruction: "Желатиныг хүйтэн усанд 10 минут дэвтээнэ." },
      {
        order: 2,
        instruction: "Сүүг дулааны зэрэгт халааж, чихэр, ванилин нэмнэ.",
      },
      { order: 3, instruction: "Бананыг буталж сүүтэй холино." },
      { order: 4, instruction: "Желатиныг нэмж, хутгаж уусгана." },
      { order: 5, instruction: "Аяганд хийж хөргөгчинд 4 цаг тавина." },
    ],
  },
  {
    _id: "3",
    title: "Махан хуурга төмстэй",
    description:
      "Үхрийн мах, төмс, лууван, сонгиноны хуурсан хоол — монгол айлын өдөр тутмын хоол.",
    author: { name: "Г. Оюунбат" },
    categories: ["Мах", "Хурдан хоол"],
    tags: ["Уламжлалт"],
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    difficulty: "easy",
    rating: 4.4,
    reviewCount: 67,
    allergens: [],
    ingredients: [
      { name: "Үхрийн мах", amount: "500", unit: "гр" },
      { name: "Төмс", amount: "4", unit: "ширхэг" },
      { name: "Лууван", amount: "2", unit: "ширхэг" },
      { name: "Сонгино", amount: "1", unit: "ширхэг" },
      { name: "Цөцгийн тос", amount: "2", unit: "хш" },
      { name: "Давс, чинжүү", amount: "1", unit: "хш" },
    ],
    steps: [
      { order: 1, instruction: "Махыг нимгэн зүсэж давс, чинжүүгээр амтална." },
      {
        order: 2,
        instruction: "Тогоонд тос халааж, махыг алтлах хүртэл хуурна.",
      },
      { order: 3, instruction: "Сонгино нэмж хүртэл хуурна." },
      {
        order: 4,
        instruction: "Төмс, луувангаа нэмж, бага галд 15 минут чанана.",
      },
      { order: 5, instruction: "Давс, чинжүүгээр амтыг тохируулна." },
    ],
  },
  {
    _id: "4",
    title: "Тарагтай хонины шөл",
    description:
      "Цагаан идээгээр тангалагтай, хялмасыг аргагүй болгосон уламжлалт хонины шөл.",
    author: { name: "С. Энхтуяа" },
    categories: ["Шөл", "Уламжлалт"],
    tags: ["Хонь"],
    cookTime: 60,
    prepTime: 15,
    servings: 5,
    difficulty: "medium",
    rating: 4.7,
    reviewCount: 203,
    allergens: ["dairy"],
    ingredients: [
      { name: "Хонины мах", amount: "800", unit: "гр" },
      { name: "Тараг", amount: "300", unit: "мл" },
      { name: "Сонгино", amount: "2", unit: "ширхэг" },
      { name: "Часнай", amount: "3", unit: "шүд" },
      { name: "Давс", amount: "1", unit: "хш" },
      { name: "Ус", amount: "1.5", unit: "л" },
    ],
    steps: [
      { order: 1, instruction: "Хонины махыг угааж, хэрчнэ." },
      { order: 2, instruction: "Усанд хийж 30 минут буцалгаж хөөс авна." },
      { order: 3, instruction: "Сонгино, часнай нэмж 20 минут чанана." },
      { order: 4, instruction: "Тарагаа аажмаар нэмж хутгана." },
      { order: 5, instruction: "Давсаар амтыг тохируулж дулаанаар хүргэнэ." },
    ],
  },
  {
    _id: "5",
    title: "Гурилтай шөл",
    description:
      "Өрхийн дотроос гаргасан тос, нарийн гурилаар хийсэн уламжлалт монгол гурилтай шөл.",
    author: { name: "Н. Болормаа" },
    categories: ["Шөл", "Гурилан хоол"],
    tags: ["Уламжлалт"],
    cookTime: 40,
    prepTime: 20,
    servings: 4,
    difficulty: "medium",
    rating: 4.3,
    reviewCount: 55,
    allergens: ["gluten"],
    ingredients: [
      { name: "Гурил", amount: "300", unit: "гр" },
      { name: "Өндөг", amount: "1", unit: "ширхэг" },
      { name: "Хонины мах", amount: "400", unit: "гр" },
      { name: "Сонгино", amount: "1", unit: "ширхэг" },
      { name: "Давс", amount: "1", unit: "хш" },
      { name: "Ус", amount: "1", unit: "л" },
    ],
    steps: [
      {
        order: 1,
        instruction: "Гурил, өндөг, давс, усаар зуурч гурил зуурна.",
      },
      {
        order: 2,
        instruction: "Гурилыг нимгэн дэлгэж жижиг дөрвөлжин хэлбэрт хэрчнэ.",
      },
      { order: 3, instruction: "Махыг буцалсан усанд хийж 20 минут чанана." },
      { order: 4, instruction: "Хэрчсэн гурилаа нэмж 10 минут чанана." },
      { order: 5, instruction: "Сонгино нэмж, давсаар амтыг тохируулна." },
    ],
  },
  {
    _id: "6",
    isPremium: true,
    title: "Тахианы карри",
    description: "Энэтхэг болон монгол орц хослуулсан ароматик тахианы карри.",
    author: { name: "Б. Чимэгэрдэнэ" },
    categories: ["Тахиа"],
    tags: ["Гадаад"],
    cookTime: 35,
    prepTime: 15,
    servings: 4,
    difficulty: "medium",
    rating: 4.9,
    reviewCount: 312,
    allergens: [],
    ingredients: [
      { name: "Тахианы мах", amount: "600", unit: "гр" },
      { name: "Карри нунтаг", amount: "2", unit: "хш" },
      { name: "Кокосын сүү", amount: "400", unit: "мл" },
      { name: "Сонгино", amount: "1", unit: "ширхэг" },
      { name: "Часнай", amount: "4", unit: "шүд" },
      { name: "Улаан лооль", amount: "2", unit: "ширхэг" },
      { name: "Цөцгийн тос", amount: "2", unit: "хш" },
    ],
    steps: [
      {
        order: 1,
        instruction: "Тахианы махыг хэсгүүдэд хэрчиж, карри нунтагаар будна.",
      },
      { order: 2, instruction: "Тогоонд тос халааж сонгино, часнай хуурна." },
      { order: 3, instruction: "Мах нэмж алтлах хүртэл хуурна." },
      { order: 4, instruction: "Улаан лооль нэмж 5 минут буцалгана." },
      { order: 5, instruction: "Кокосын сүү нэмж 20 минут бага галд чанана." },
    ],
  },
  {
    _id: "7",
    title: "Буузны дүүргэлт — уламжлалт",
    description:
      "Гурван мах холилдсон, сонгино, часнай бүхий уламжлалт буузны дүүргэлт.",
    author: { name: "Д. Нарантуяа" },
    categories: ["Үндэсний хоол", "Гурилан хоол"],
    tags: ["Уламжлалт", "Мах"],
    cookTime: 30,
    prepTime: 40,
    servings: 8,
    difficulty: "medium",
    rating: 4.9,
    reviewCount: 418,
    allergens: ["gluten"],
    ingredients: [
      { name: "Үхрийн мах", amount: "400", unit: "гр" },
      { name: "Хонины мах", amount: "200", unit: "гр" },
      { name: "Сонгино", amount: "2", unit: "ширхэг" },
      { name: "Часнай", amount: "2", unit: "шүд" },
      { name: "Гурил", amount: "500", unit: "гр" },
      { name: "Давс, чинжүү", amount: "1", unit: "хш" },
    ],
    steps: [
      { order: 1, instruction: "Гурилаа зуурч 30 минут амраана." },
      {
        order: 2,
        instruction: "Махыг жижиглэж, сонгино, часнай, давс нэмж холино.",
      },
      { order: 3, instruction: "Гурилаа нимгэн дэлгэж тойрог хэлбэрт хэрчнэ." },
      { order: 4, instruction: "Дүүргэлт хийж буузыг боодог болгоно." },
      { order: 5, instruction: "Уурын зуухнаас 30 минут жигнэнэ." },
    ],
  },
  {
    _id: "8",
    title: "Цагаан будаатай хоол",
    description:
      "Хуурсан тахиа, хүнсний ногоо, өндөгтэй хосолсон Ази маягийн будаатай хоол.",
    author: { name: "Г. Оюунбат" },
    categories: ["Хурдан хоол"],
    tags: ["Ази"],
    cookTime: 15,
    prepTime: 10,
    servings: 3,
    difficulty: "easy",
    rating: 4.2,
    reviewCount: 44,
    allergens: ["egg", "soy"],
    ingredients: [
      { name: "Цагаан будаа", amount: "2", unit: "аяга" },
      { name: "Тахианы мах", amount: "200", unit: "гр" },
      { name: "Өндөг", amount: "2", unit: "ширхэг" },
      { name: "Лууван", amount: "1", unit: "ширхэг" },
      { name: "Соёо", amount: "3", unit: "хш" },
      { name: "Ногооны тос", amount: "2", unit: "хш" },
    ],
    steps: [
      { order: 1, instruction: "Будааг урьдчилан чанаж хөргөнө." },
      { order: 2, instruction: "Тогоонд тос халааж, тахиа хуурна." },
      { order: 3, instruction: "Хүнсний ногоо нэмж 3 минут хуурна." },
      { order: 4, instruction: "Будаа нэмж хутгана." },
      { order: 5, instruction: "Өндөг нэмж хутгаж, соёо цацна." },
    ],
  },
];
